XDG_CONFIG_HOME="${HOME}/.config"
XDG_DATA_HOME="${HOME}/.local/share"
XDG_STATE_HOME="${HOME}/.local/state"
XDG_CACHE_HOME="${HOME}/.cache"
ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
PATH="${PATH}:/home/usmon/.local/bin:/home/usmon/.local/share/JetBrains/Toolbox/scripts"
ZINIT_HOME="${XDG_DATA_HOME}/zinit/zinit"
STARSHIP_HOME="${XDG_CONFIG_HOME}/starship"
